In [2]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
mean = np.mean(arr)
print(mean)

2.5


In [4]:
rearr = arr.reshape(4,1)
print(rearr)

[[1]
 [2]
 [3]
 [4]]


In [5]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,3,2,1])
result = arr1*arr2
print(result)

[4 6 6 4]


In [6]:
maxv = np.max(arr2)
print(maxv)

4


In [8]:
matrix = np.array([[1,2],[3,4]])
tmatrix = np.transpose(matrix)
print(tmatrix)
print(matrix)

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]


In [10]:
se = np.arange(0,10,2)
print(se)

[0 2 4 6 8]


In [14]:
arr = np.array([5,7,4,3,6,8])
sarr = np.sort(arr)
print(sarr)


[3 4 5 6 7 8]


In [15]:
uni = np.unique(arr)
print(uni)

[3 4 5 6 7 8]
